# Generated by Django 5.2.7 on 2025-10-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
